[project]
name = "args"

[target.args]
type = "interface"
alias = "args::args"
include-directories = ["include"]
compile-features = ["cxx_std_11"]

[target.example]
type = "executable"
condition = "root"
sources = ["src/example.cpp"]
link-libraries = ["args::args"]
